spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${uaa.uri}/oauth/token
      client:
        registration:
          a:
            provider: uaa
            client-id: ${auth.client-id}
            client-secret: ${auth.client-secret}
            authorization-grant-type: client_credentials
        provider:
          uaa:
            issuer-uri: ${uaa.uri}/oauth/token
